# Generated by Django 5.2 on 2025-09-01 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Owner',
            fields=[
                ('id_owner', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name_owner', models.CharField(max_length=40)),
                ('Email_owner', models.EmailField(max_length=50, unique=True)),
                ('is_google_user', models.BooleanField(default=False)),
                ('Enrolled_Date_owner', models.DateTimeField(default=datetime.datetime.now, verbose_name='Year Joined')),
                ('gender_owner', models.CharField(max_length=1)),
                ('active_owner', models.BooleanField(default=True)),
                ('phone_owner', models.CharField(blank=True, max_length=10)),
                ('profile_picture_owner', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('status_owner', models.CharField(choices=[('active', 'Active'), ('not_active', 'Not Active')], default='active', max_length=20)),
            ],
            options={
                'verbose_name': 'Project Owner',
                'ordering': ['Enrolled_Date_owner'],
            },
        ),
    ]
