# Generated by Django 5.2 on 2025-09-01 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developers', '0001_initial'),
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('dev', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='developers.developer')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='owners.project_owner')),
            ],
            options={
                'unique_together': {('dev', 'owner')},
            },
        ),
    ]
