# Generated by Django 5.2 on 2025-09-01 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id_dev', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name_dev', models.CharField(max_length=40)),
                ('email_dev', models.EmailField(max_length=50, unique=True)),
                ('is_google_user', models.BooleanField(default=False)),
                ('enrolled_date_dev', models.DateTimeField(default=datetime.datetime.now, verbose_name='Year Joined')),
                ('gender_dev', models.CharField(max_length=1)),
                ('active_dev', models.BooleanField(default=True)),
                ('phone_dev', models.CharField(blank=True, max_length=10)),
                ('profile_picture_dev', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('status_dev', models.CharField(choices=[('active', 'Active'), ('not_active', 'Not Active')], default='active', max_length=20)),
                ('skills', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Developer',
                'ordering': ['enrolled_date_dev'],
            },
        ),
    ]
