# Generated by Django 5.2 on 2025-09-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developers', '0001_initial'),
        ('main', '0001_initial'),
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='projects',
            field=models.ManyToManyField(related_name='developers', through='main.Registration', to='owners.project_owner'),
        ),
    ]
